- .circleci/config.yml
- .eslintrc.js
- demo/src/components/sections/InputSection/InputSection.vue
- demo/src/views/Home.vue
- package.json
- src/components/inputs/LabeledInput.vue
- tests/example.spec.js
- yarn.lock
- Added dropdown and multiselect usage in demo (probably going to create wrappers for them in a near future)
- Added eslint config
> LOG-3968 | Added dropdowns to demo

- src/components/inputs/LDatePickerDay.vue
- util/date.util.ts
- Corrigido layout do datepicker de dia
- [LOG-7750](https://logcomex.atlassian.net/browse/LOG-7750)
> (LOG-7750) - Corrigido layout do datepicker de dia

- src/components/modal/LModal.vue
- src/components/modal/LModalContent.vue
- Passagem de modal do searchx para o design system
- [LOG-7608](https://logcomex.atlassian.net/browse/LOG-7608)
> (LOG-7608) - Passagem de modal do searchx para o design system

- src/components/modal/LModal.vue
- src/components/modal/LModalContent.vue
- src/components/modal/index.js
- Passagem de modal do searchx para o design system
- [LOG-7608](https://logcomex.atlassian.net/browse/LOG-7608)
> (LOG-7608) Passagem de modal do searchx para o design system

- src/components/modal/LModal.vue
- src/components/modal/LModalContent.vue
- src/components/modal/index.js
- src/index.js
-  Correção na exportação de modal
- [LOG-7608](https://logcomex.atlassian.net/browse/LOG-7608)
> (LOG 7608) -  Correção na exportação de modal

- package.json
- featureN
- [LOG-XX](https://logcomex.atlassian.net/browse/LOG-XX)
> (LOG-7967) - Adicionado files para incluir dist

- demo/src/scss/_global.scss
- src/assets/scss/_globals.scss
- src/assets/scss/_main.scss
- src/components/cards/LCard.vue
- src/components/charts/LResumeChart.vue
- src/components/charts/LResumeLine.vue
- src/components/charts/index.js
- src/index.js
- test/components/charts/lResumeChart.spec.ts
- vue.config.js
- Adiciona chart resumido
- [LOG-8020](https://logcomex.atlassian.net/browse/LOG-8020)
> (LOG-8020) - Adiciona chart resumido

- README.md
- src/assets/scss/_variables.scss
- src/components/charts/LRouteChart.vue
- src/components/charts/LRouteChartHeader.vue
- src/components/charts/LRouteChartLine.vue
- src/components/charts/index.js
- Adicionado componente com listagem de rotas
- [LOG-8028](https://logcomex.atlassian.net/browse/LOG-8028)
> (LOG-8028) - Adicionado componente com listagem de rotas

- src/components/alerts/LAlert.vue
- src/components/alerts/index.js
- src/index.js
- test/components/alerts/alert.spec.ts
- Externalizado componente LAlert.vue
- [LOG-8249](https://logcomex.atlassian.net/browse/LOG-8249)
> (LOG-8249) - Component FAlert

- src/components/charts/LResumeChart.vue
- Ajuste de CSS
- [LOG-8401](https://logcomex.atlassian.net/browse/LOG-8401)
> (LOG-8401) - Ajuste de CSS

- README.md
- src/components/charts/LRouteChart.vue
- src/components/charts/LRouteChartHeader.vue
- src/components/charts/LRouteChartLine.vue
- test/components/charts/lRouteChart.spec.ts
- Add arrow effect to lines
- [LOG-8028](https://logcomex.atlassian.net/browse/LOG-8028)
> (LOG-8028) - Add arrow effect to lines

- README.md
- src/assets/scss/_variables.scss
- src/components/tables/LTable.vue
- src/components/tables/index.js
- src/index.js
- test/components/tables/lTable.spec.ts
- Adicionado tabela
- [LOG-7789](https://logcomex.atlassian.net/browse/LOG-7789)
> (LOG-7789) - Adicionado tabela

- README.md
- src/assets/scss/_globals.scss
- src/components/cards/LCard.vue
- src/components/charts/LResumeChart.vue
- src/components/charts/LRouteChart.vue
- src/components/charts/LRouteChartHeader.vue
- src/components/charts/LRouteChartLine.vue
- Adicionado tooltip e corrigido altura
- [LOG-8476](https://logcomex.atlassian.net/browse/LOG-8476)
> (LOG-8476) - Adicionado tooltip e corrigido altura

- README.md
- src/components/cards/LCard.vue
- src/components/charts/LBarChart.vue
- src/components/charts/LBarChartLine.vue
- src/components/charts/index.js
- test/components/charts/lBarChart.spec.ts
- Adicionado grafico de barras
- [LOG-8095](https://logcomex.atlassian.net/browse/LOG-8095)
> (LOG-8095) - Adicionado grafico de barras

- src/assets/scss/_globals.scss
- src/components/charts/LLinearChart.vue
- src/components/charts/LLinearChartExpand.vue
- src/components/charts/LLinearChartLine.vue
- src/components/charts/index.js
- src/components/loadings/LLoading.vue
- src/components/loadings/index.js
- src/index.js
- test/components/charts/lLinearChart.spec.ts
- test/components/charts/lLinearChartExpand.spec.ts
-  Adicionado grafico linear
- [LOG-8509](https://logcomex.atlassian.net/browse/LOG-8509)
> (LOG-8509) - Adicionado grafico linear

- src/components/charts/LBarChart.vue
- src/components/charts/LBarChartLine.vue
- src/components/tables/LSimpleTable.vue
- src/components/tables/index.js
- test/components/charts/lBarChart.spec.ts
- Alterado componente de tabela simples
- [LOG-8505](https://logcomex.atlassian.net/browse/LOG-8505)
> (LOG-8505) - Alterado componente de tabela simples

- src/components/inputs/LSelectNamed.vue
- src/components/inputs/index.js
- test/components/inputs/lSelectNamed.spec.ts
- test/components/inputs/lSelectSolo.spec.ts
- Adicionado select named
- [LOG-7790](https://logcomex.atlassian.net/browse/LOG-7790)
> (LOG-7790) - Adicionado select named

- src/components/cards/LCard.vue
- src/components/charts/LResumeChart.vue
- src/components/charts/LRouteChart.vue
- test/components/charts/lResumeChart.spec.ts
- Ajustes de graficos
- [LOG-8786](https://logcomex.atlassian.net/browse/LOG-8786)
> (LOG-8786) - Ajustes de graficos

- src/components/charts/LLinearChartLine.vue
- Ajuste de css
- [LOG-8899](https://logcomex.atlassian.net/browse/LOG-8899)
> (LOG-8899) - Ajuste de css

- src/components/inputs/LDatePickerMonth.vue
- src/components/inputs/LSelectNamed.vue
- Corrigido laterais no datepicker
- [LOG-8094](https://logcomex.atlassian.net/browse/LOG-8094)
> (LOG-8094) - Corrigido laterais no datepicker

- src/components/inputs/LInputLoaded.vue
- src/components/inputs/index.js
- test/components/inputs/lInputLoaded.spec.ts
- Adicionado com carregamento de items
- [LOG-7220](https://logcomex.atlassian.net/browse/LOG-7220)
> (LOG-7220) - Adicionado com carregamento de items

- src/assets/scss/_globals.scss
- src/assets/scss/_variables.scss
- src/components/buttons/LButtonSelect.vue
- src/components/buttons/index.js
- src/components/inputs/LCheckboxList.vue
- src/components/inputs/LDropdownCheckbox.vue
- src/components/inputs/LInputSolo.vue
- src/components/inputs/index.js
- test/components/buttons/lButtonSelect.spec.ts
- test/components/inputs/lCheckboxList.spec.ts
- test/components/inputs/lDropdownCheckbox.spec.ts
- Adicionado dropdown de checkbox
- [LOG-8916](https://logcomex.atlassian.net/browse/LOG-8916)
> (LOG-8916) - Adicionado dropdown de checkbox

- src/components/charts/LBarChart.vue
- src/components/charts/LBarChartLine.vue
- test/components/charts/lBarChart.spec.ts
- Criação de parâmetro outros para bar line chart que tenha expansão
- [LOG-8905](https://logcomex.atlassian.net/browse/LOG-8905)
> (LOG-8905) - Expandir Lista NCM

- src/components/charts/LCircularChart.vue
- src/components/charts/index.js
- test/components/charts/lCircularChart.spec.ts
- Adicionado grafico circular de porcentagem
- [LOG-8865](https://logcomex.atlassian.net/browse/LOG-8865)
> (LOG-8865) - Adicionado grafico circular de porcentagem

- src/components/charts/LLinearChartLine.vue
- Disponibilidade para mostar ou não detalhamento da linha do LLinearChartLine.vue
- [LOG-9158](https://logcomex.atlassian.net/browse/LOG-9158)
> (LOG-9158) - Ajuste para o gráfico de tags

- src/components/charts/LLinearChart.vue
- src/components/charts/LLinearChartLine.vue
- test/components/charts/lLinearChart.spec.ts
- Corrigido altura das linhas e ajustes nas labels
- [LOG-8595](https://logcomex.atlassian.net/browse/LOG-8595)
> (LOG-8595) - Corrigido altura das linhas e ajustes nas labels

- .github/PULL_REQUEST_TEMPLATE.md
- src/components/buttons/LButton.vue
- src/components/buttons/index.js
- test/components/buttons/lButton.spec.ts
- Adicionado botão padrao do sistema
- LOG-9255
> (LOG-9255) - Adicionado botão padrao do sistema

- package.json
- yarn.lock
- Definindo dependencias para serem instaladas
- LOG-9254
> (LOG-9254) - Definindo dependencias para serem instaladas

- src/components/tables/LTable.vue
- Ajuste largura da tabela e não ter quebra de linhas
- LOG-9467
> (LOG-9467) - Ajuste largura da tabela e não ter quebra de linhas

- src/components/tables/LTable.vue
- test/components/tables/lTable.spec.ts
- Adicionado tooltip para os itens truncados
- LOG-9467
> (LOG-9467) - Adicionado tooltip para os itens truncados

- src/components/tables/LTable.vue
- Corrigido validação para tooltip
- LOG-9616
> (LOG-9616) - Corrigido validação para tooltip

- .github/.gitmessage
- src/components/charts/LGeneralChart.vue
- src/components/charts/index.js
- test/components/charts/lGeneralChart.spec.ts
- Externalizado componente generalData e adicionado tipo de valor
- LOG-9555
> (LOG-9555) - Externalizado componente generalData e adicionado tipo de valor

- src/locale/en.js
- src/locale/index.js
- src/locale/pt.js
- Implementado tradução no design system
- LOG-9554
> (LOG-9554) - Implementado tradução no design system

- src/assets/scss/_globals.scss
- src/components/inputs/LBorderedInput.vue
- src/components/inputs/LCheckbox.vue
- src/components/inputs/LInputLoaded.vue
- src/components/inputs/LInputTag.vue
- src/components/inputs/index.js
- test/components/inputs/lCheckbox.spec.ts
- test/components/inputs/lInputTag.spec.ts
- Componentizado itens do fieldmanager
- LOG-9558
> (LOG-9558) - Componentizado itens do fieldmanager

- src/components/cards/LCardHeader.vue
- src/components/charts/LCircularChart.vue
- test/components/charts/lCircularChart.spec.ts
- Corrigido items não aparecendo
- LOG-9786
Subtask afetada - LOG-10265
> (LOG-9786) - Corrigido items não aparecendo

- src/components/inputs/LInputLoaded.vue
- test/components/inputs/lInputLoaded.spec.ts
- Removido texto após filtrar
- LOG-9599
> (LOG-9599) - Removido texto após filtrar

- src/components/cards/LCard.vue
- Adicionado important no box-shadow
- LOG-9850
> (LOG-9850) - Adicionado important no box-shadow

- src/components/charts/LCircularChart.vue
- Adicionado size para os circulos
- LOG-9779
> (LOG-9779) - Adicionado size para os circulos

- src/components/charts/LCircularChart.vue
- Ajustado tamanho dos icones
- LOG-9786
> (LOG-9786) - Ajustado tamanho dos icones

- src/components/inputs/LCheckbox.vue
- test/components/inputs/lCheckbox.spec.ts
- Adicionado opção de array de objetos
- LOG-9849
> (LOG-9849) - Adicionado opção de array de objetos

- src/components/tables/LTable.vue
- diminuido header
- LOG-10001
> (LOG-10001) - diminuido header

- src/components/tables/LTable.vue
- Corrigido cores da divisão da tabela
- LOG-10001
> (LOG-10001) - Corrigido cores da divisão da tabela

- src/components/inputs/LCheckboxList.vue
- src/components/inputs/LDropdownCheckbox.vue
- src/components/tables/LTable.vue
- test/components/inputs/lCheckboxList.spec.ts
- Adicionado itens recebidos para as colunas
- LOG-10011
> (LOG-10011) - Adicionado itens recebidos para as colunas

- .github/PULL_REQUEST_TEMPLATE.md
- src/components/charts/LRouteChartHeader.vue
- test/components/charts/lRouteChart.spec.ts
- Removido seta e quebra de linha
- LOG-10115
> (LOG-10115) - Removido seta e quebra de linha

- src/components/charts/LRouteChartLine.vue
- Realizar o ajuste para visualização do %
- [LOG-8949](https://logcomex.atlassian.net/browse/LOG-8949)
- [LOG-10719](https://logcomex.atlassian.net/browse/LOG-10719)
> (LOG-8949) - Realizar o ajuste para o texto não ultrapassar o limite da área visível.

- src/components/buttons/LButton.vue
- Adicionado bind pra atributos
- LOG-10117
- LOG-10167
> (LOG-10117) - Adicionado bind pra atributos

- src/components/inputs/LDatePickerDay.vue
- test/components/inputs/ldatePickerDay.spec.ts
- Removido periodos do datepicker
- LOG-10675
- LOG-10729
> (LOG-10675) - Removido periodos do datepicker

- src/components/alerts/LAlert.vue
- Adicionado absolute no componente LAlert
- LOG-10969
- LOG-11090
> (LOG-10969) - Adicionado absolute no componente LAlert

- src/components/inputs/LInputLoaded.vue
- Adicionado parametro para não adicionar item novo
- LOG-11196
- LOG-11199
> (LOG-11196) - Adicionado parametro para não adicionar item novo

- .github/workflows/npm-publish.yml
- src/components/charts/LRouteChart.vue
- test/components/charts/lRouteChart.spec.ts
- Removido header do card de rotas
- LOG-10939
- LOG-11070
> (LOG-10939) - Removido header do card de rotas

- src/components/charts/LLinearChartExpand.vue
- Removido USD
- LOG-11308
- LOG-11310
> (LOG-11308) - Removido USD

- utils/date.util.ts
- Adicionado console e validação para tentativa de debug
- LOG-10983
- LOG-11080
> (LOG-10983) - Adicionado console e validação para tentativa de debug

- src/components/inputs/LInputLoaded.vue
- Corrigido validação para Array no filterloaded
- LOG-11561
- LOG-11563
> (LOG-11561) - Corrigido validação para Array no filterloaded

- package.json
- src/components/inputs/LCheckboxList.vue
- src/components/tables/LTable.vue
- test/components/inputs/lCheckboxList.spec.ts
- yarn.lock
- Corrigido items selecionado com busca
- LOG-10914
- LOG-11074
> (LOG-10914) - Corrigido items selecionado com busca

- src/components/modal/LModal.vue
- Adição de propriedade de load no card do modal
- LOG-10881
- LOG-11607
> (LOG-11606) - Adição de propriedade loading no componente LModal

- src/components/tables/LTable.vue
- test/components/tables/lTable.spec.ts
- Foi criado a propridade itemsPerPage no componente LTable.vue
- LOG-9812
- LOG-11599
> (LOG-12046) - Foi criado a propridade itemsPerPage no componente LTable.vue

- enum/table.enum.ts
- package.json
- src/assets/scss/_globals.scss
- src/components/bars/LProgressBar.vue
- src/components/bars/index.js
- src/components/cards/LCardHeader.vue
- src/components/charts/LBarChartLine.vue
- src/components/inputs/LDropdownCheckbox.vue
- src/components/tables/LTable.vue
- src/index.js
- yarn.lock
- Atualizado componentes e tabela padrão do sistema
- LOG-10753
- LOG-11354
> (LOG-10753) - Atualizado componentes e tabela padrão do sistema

- .gitignore
- src/components/tables/LTable.vue
- Ajuste para limpar a flag de ordenação
- [LOG-11041](https://logcomex.atlassian.net/browse/LOG-11041)
- [LOG-11408](https://logcomex.atlassian.net/browse/LOG-11408)
> (LOG-12772) - Não continua ordenado após pesquisa

- src/components/tables/LTable.vue
- Corrigido  keys do componente LTable
- LOG-12871
- LOG-12879
> (LOG-12871) - Corrigido  keys do componente LTable

- README.md
- src/components/buttons/LButton.vue
- src/components/buttons/LButtonIcon.vue
- test/components/buttons/lButton.spec.ts
- utils/date.util.ts
- Alterado parametros e adicionado docs
- LOG-10657
- LOG-11083
> (LOG-10657) - Alterado parametros e adicionado docs

- src/components/tables/LTable.vue
- test/components/tables/lTable.spec.ts
- Corrigido layout do botão de download
- Adicionado teste unitário para botão de download
- LOG-10753
- LOG-11354
>  (LOG-10753) - Corrigido layout do botão de download

- src/components/charts/LLinearChartExpand.vue
- Fixando header do v-simple-table no LLinearChartExpand
- LOG-11942
- LOG-12165
> (LOG-12163) Header fixado no topo

- src/components/modal/LModal.vue
- Ajuste para bloquear botão Solicitar Excel ao realizar requisição
- [LOG-11128](https://logcomex.atlassian.net/browse/LOG-11128)
- [LOG-11401](https://logcomex.atlassian.net/browse/LOG-11401)
> (LOG-13438) - Tela modal demora sumir

- src/components/cards/LCardHeader.vue
- utils/date.util.ts
- Correção de dia máximo para ano mês
- LOG-11990
- LOG-12202
> (LOG-13773) - Correção de dia máximo para ano mês

- src/components/charts/LLinearChartExpand.vue
- z-index da classe do header alterado para 0
- LOG-13807
- LOG-13955
> (LOG-13807) Corrigido header por cima de outros elementos

- src/components/buttons/LButton.vue
- src/components/inputs/LInputButton.vue
- src/components/inputs/index.js
- Criado novo componente de input com botão do lado
- Alterado props do LButton.vue
- [LOG-14098](https://logcomex.atlassian.net/browse/LOG-14098)
- [LOG-13960](https://logcomex.atlassian.net/browse/LOG-13960)
> (LOG-14098) - Criar component no design-system

- src/components/inputs/LInputButton.vue
- Ajustado retorno do método computed dos listeners
- [LOG-14098](https://logcomex.atlassian.net/browse/LOG-14098)
- [LOG-13960](https://logcomex.atlassian.net/browse/LOG-13960)
> (LOG-14109) - Ajustar os listeners do componente

- docs/stories/components/charts/LBarChart.stories.js
- docs/stories/components/charts/LLinearChart.stories.js
- docs/stories/components/charts/LLinearChartExpand.stories.js
- docs/stories/components/charts/LRouteChart.stories.js
- LLinearChart e LLinearChatExpand documentados separadamente
- LBarChart  e LRouteChart com correções na doc
- LOG-14006
- LOG-14015
> (LOG-14006) Design System :: Documentar componente Barras

- docs/stories/components/buttons/LButton.stories.js
- docs/stories/components/buttons/LButtonIcon.stories.js
- docs/stories/components/tables/LTable.stories.js
- LButton documentado com suas variações
- LButtonIcon documentado
- LTable comentado a fim de parar de dar os erros de build
- LOG-14009
- LOG-14012
> (LOG-14009) Design System :: Documentar componente Botões

- docs/stories/components/cards/LCard.stories.js
- LCard documentado
- LOG-14010
- LOG-14018
> (LOG-14010) - Design System :: Documentar componente Cards

- docs/stories/components/loadings/LLoading.stories.js
- Criação da documentação do LLoading
- LOG-14020
- LOG-14484
> (LOG-14020) - Design System :: Documentar componente loadings

- src/components/charts/LLinearChartLine.vue
- Ajuste na margem da coluna de informações para respeitar área delimitada pelo 
chart
- [LOG-14049](https://logcomex.atlassian.net/browse/LOG-14049)
- [LOG-14401](https://logcomex.atlassian.net/browse/LOG-14401)
> (LOG-14400) - Ajustar layout para respeitar area

- docs/stories/components/tags/LTag.stories.js
- Design System :: Documentar componente tag
- LOG-14024
- LOG-14491
> (LOG-14024) - Design System :: Documentar componente tag

- docs/stories/components/tags/LTag.stories.js
- Nome do componente no storybook deixar como Tag apenas
- Mudar a story  de "Number" para "With Number"
- Mudar a story "Icon Custom LInk" para "With custom link"
- Desabilitar o slot default na doc se ele não é usado
- LOG-14024
- LOG-14601
> (LOG-14024) - Documentar componente tag

- docs/stories/components/filters/LLabeledChip.stories.js
- Documentar componente LLabeledChip
- LOG-14016
- LOG-14479
> (LOG-14016) - Documentar componente Filters

- src/components/tables/LTable.vue
- test/components/tables/lTable.spec.ts
- Mover e ordenar as colunas (salvar)
- LOG-12134
- LOG-14815
> (LOG-12134) - Mover e ordenar as colunas (salvar)

- src/components/buttons/LButtonIcon.vue
- Alteração no componente LButtonIcon.vue impactando a tela inicial do search
- LOG-16204
- LOG-16368
> (LOG-16429) Alteração no componente LButtonIcon.vue impactando a tela inicial do search

- src/components/tables/LTable.vue
- Corrigido bug ao adiciona coluna e arrastar
- LOG-15758
- LOG-16257
> (LOG-15758) - Corrigido bug ao adicionar coluna e arrastar

- docs/stories/components/charts/LLinearChartExpand.stories.js
- src/components/charts/LLinearChartExpand.vue
- Adicionado altura maxima pra tabela do card expandido
- Ajustado z-index do header da tabela
- LOG-16296
- LOG-16878
> (LOG-16296) - Adicionado altura maxima pra tabela do card expandido

- docs/stories/components/charts/LLinearChart.stories.js
- docs/stories/components/charts/LLinearChartExpand.stories.js
- src/components/charts/LLinearChart.vue
- src/components/charts/LLinearChartExpand.vue
- src/components/charts/LLinearChartLine.vue
- test/components/charts/lLinearChart.spec.ts
- test/components/charts/lLinearChartExpand.spec.ts
- Adição de props para controle de visualização do ToolTip
- Adição de tooltip para exibição de detalhes recebidos no payload padrão
- [LOG-11970](https://logcomex.atlassian.net/browse/LOG-11970)
- [LOG-12262](https://logcomex.atlassian.net/browse/LOG-12262)
> (LOG-12260) - Adicionar o tooltip apenas quando for TEUS

- src/components/inputs/LDatePickerDay.vue
- test/components/inputs/lDatePickerDay.spec.ts
- utils/date.util.ts
- Corrigido bug de data invertida
- LOG-16670
- LOG-16886
> (LOG-16670) - Corrigido bug de data invertida

- docs/stories/components/inputs/LDatePickerDay.stories.js
- src/components/inputs/LDatePickerDay.vue
- src/components/inputs/LInputLoaded.vue
- test/components/inputs/lDatePickerDay.spec.ts
- Adicionada possibilidade do datepicker ser fechado de acordo com evento no componente pai
- Adicionado o atributo attach ao LInputLoaded
- Documentação atualizada
- Teste unitário
- LOG-16466
- LOG-16872
> (LOG-16466) List box fica em cima da tela

- package.json
- utils/date.util.ts
- Date Picker não funciona no Safari
- LOG-11364
- LOG-16898
> (LOG-11364) - Date Picker não funciona no Safari

- docs/stories/components/charts/LLinearChart.stories.js
- package.json
- src/components/charts/LLinearChart.vue
- src/components/charts/LLinearChartLine.vue
- test/components/charts/lLinearChart.spec.ts
> Release 1.0.0

- docs/stories/components/alerts/LAlert.stories.js
- docs/stories/components/inputs/LLabeledInput.stories.js
- docs/stories/components/inputs/LSelectNamed.stories.js
- src/components/alerts/LAlert.vue
- src/components/inputs/LLabeledInput.vue
- src/components/inputs/LSelectNamed.vue
- Atualização da documentação dos components alterados
- Atualização dos components para receber as props de que permita os desabilitar e alteração para que o select possa receber um obj como selected
- LOG-17414
- LOG-18371
> (LOG-17414) - Alterar Senha / Perfil

- package.json
- src/components/buttons/LButton.vue
- src/components/modal/LModal.vue
- test/components/modal/LModal.spec.ts
- Add trigger to remove shadow on LButton
- Add unit test to cehnges on LModal
- LOG-15297
- LOG-18416
> (LOG-15297) - Add trigger to remove shadow 

- src/components/modal/LModal.vue
- test/components/modal/LModal.spec.ts
- Adicionado props
- Adicionado teste unitário
- [LOG-14874](https://logcomex.atlassian.net/browse/LOG-14874)
- [LOG-16188](https://logcomex.atlassian.net/browse/LOG-16188)
> (LOG-20805) Ajustar o modal para não exibir o btn cancelar

- src/components/charts/LLinearChart.vue
- src/components/charts/LLinearChartExpand.vue
- src/components/charts/LLinearChartLine.vue
- Alterado css do LLinearchart
- [LOG-20799](https://logcomex.atlassian.net/browse/LOG-20799)
- [LOG-21854](https://logcomex.atlassian.net/browse/LOG-21854)
Não é preciso de teste por ser uma alteração de css
> (LOG-20799) - Search e Expo :: Tabela que traz outros expandido esta quebrando layout padrão

- src/components/cards/LCard.vue
- test/components/cards/lCard.spec.ts
- Adicionado props
- Adicionado teste unitário
- [LOG-19366](https://logcomex.atlassian.net/browse/LOG-19366)
- [LOG-20347](https://logcomex.atlassian.net/browse/LOG-20347)
> (LOG-21985) Aplicar exibição do slot dentro do LCard

- src/components/cards/LCard.vue
- Adicionando diretiva v-on no l-card
- LOG-23700
- LOG-22382
> (LOG-23700) Correção de defeito Card não clicável

- docs/stories/components/modals/LModal.stories.js
- src/components/modal/LModal.vue
- test/components/modal/LModal.spec.ts
- nova prop closeOnOutsideClick
- documentação atualizada
- testes unitários
- LOG-23659
- LOG-23660
- LOG-22014
> (LOG-16780) Plataforma Tela Login/Cadastro/Redefinir Senha

- package.json
- src/components/inputs/LDatePickerMonth.vue
- Correção da regra de filtro para pegar a data limite no DatePicker.
- LOG-22503
- LOG-22671
> (LOG-22670) - Correção da regra de filtro para pegar a data limite no DatePicker.

- docs/stories/components/charts/LBarChart.stories.js
- src/components/charts/LBarChart.vue
- src/components/charts/LBarChartLine.vue
- src/components/tables/LSimpleTable.vue
- test/components/charts/lBarChart.spec.ts
- test/components/tables/lSimpleTable.spec.ts
- Adicionado a opção de clicar no título no LBarChart e LSimpleTable.
- Implementado a opção de passar se é um cursor pointer ou não pelas props do LBarChart e LSimpleTable.
- LOG-22523
- LOG-22531
> (LOG-22525) - Adicionado a opção de clicar no título no LBarChart e LSimpleTable.

- src/components/cards/LCardHeader.vue
- src/components/charts/LLinearChartLine.vue
- Corrige tamanho de texto e colors
- LOG-26068
- LOG-26260
- LOG-26702
- LOG-26704
> (LOG-26068) - Corrige tam de texto e colors

- src/components/modal/LModal.vue
- Correção para tornar a prop OverlayColor dinâmica
- LOG-23549
- LOG-23547
> (LOG-22722) - Correção para tornar a prop OverlayColor dinâmica

- docs/stories/components/charts/LLinearChart.stories.js
- src/components/charts/LLinearChart.vue
- test/components/charts/lLinearChart.spec.ts
- Implementação da lista de itens não clicáveis no LinearChart.
- LOG-27413
- LOG-28031
> (LOG-28026) - Implementação da lista de itens não clicáveis no LinearChart.

- docs/stories/components/inputs/LInputLoaded.stories.js
- src/components/inputs/LInputLoaded.vue
- test/components/inputs/lInputLoaded.spec.ts
- Removendo icone do LInputLoaded quando for searchOnInput
- LOG-24218
- LOG-24556
> (LOG-24218) Removendo icone search-on-input

- src/components/inputs/LInputLoaded.vue
- test/components/inputs/lInputLoaded.spec.ts
- Adicionando validações para a informação de minimo de caracteres aparecer apenas quando for necessário
- LOG-26624
- LOG-26625
- LOG-26627
> (LOG-24214) Melhoria componente autocomplete

- docs/stories/components/inputs/LDatePickerDay.stories.js
- src/components/inputs/LDatePickerDay.vue
- src/components/inputs/LDatePickerMonth.vue
- Titulo autoexplicativo
- LOG-29223
- LOG-29467
> (LOG-29223) Adicionando prop p/ setar locale dos DatePickers

- docs/stories/components/charts/LLinearChartExpand.stories.js
- src/components/charts/LLinearChartExpand.vue
- test/components/charts/lLinearChartExpand.spec.ts
- Implementação da lista de itens não clicáveis no LinearChartExpand.
- Implementação do Teste unitário.
- Ajuste da validação para o eventClick.
- LOG-27413
- LOG-28031
> (LOG-29064) - Implementação da lista de itens não clicáveis no LinearChartExpand.

- docs/stories/components/tables/LTableNew.stories.js
- src/components/tables/LTableNew.vue
- src/components/tables/index.js
- test/components/tables/lTableNew.spec.ts
- Criado nova tabela base
- LOG-29189
- LOG-29486
> (LOG-29189) - Criado nova tabela base

- docs/stories/components/inputs/LCheckboxList.stories.js
- docs/stories/components/inputs/LDropdownCheckbox.stories.js
- src/components/inputs/LCheckboxList.vue
- src/components/inputs/LDropdownCheckbox.vue
- test/components/inputs/lCheckboxList.spec.ts
- Alteração nos componentes para emitir do LCheckboxList
- Alteração nas documentações e no teste
- Incluindo validação na hora da emitir
- LOG-29175
- LOG-28423
> (LOG-29175) - Alteração nos componentes LCheckboxList

- .github/workflows/npm-publish-beta.yml
> (LOG-28707) - add access token

- .github/workflows/npm-publish-beta.yml
- package.json
> build to homol

- README.md
> build beta

- package.json
> 1.x version to homol

- README.md
> build to beta

- src/components/charts/LBarChart.vue
- src/components/charts/LBarChartLine.vue
- test/components/charts/lBarChart.spec.ts
- test/components/charts/lBarChartLine.spec.ts
- Corrigido teste unitário
- Alterado layout do grafico
- LOG-29456
- LOG-30270
> (LOG-29456) - Alterado layout do grafico

- docs/stories/components/inputs/LInputLoaded.stories.js
- src/components/inputs/LInputLoaded.vue
- src/components/inputs/LInputTag.vue
- src/components/inputs/LLabeledSelect.vue
- src/components/inputs/LLabeledTextarea.vue
- src/components/inputs/index.js
- src/components/modal/LModal.vue
- test/components/inputs/lInputLoaded.spec.ts
- test/components/modal/LModal.spec.ts
- Implementação do formulário
- Adiciona text área
- LOG-28845
- LOG-29061
> (LOG-28845) - Cadastro unitário de embarques

- src/components/tables/LTableNew.vue
- Corrigido defeitos de layout
- LOG-29189
- LOG-29486
> (LOG-29189) - Corrigido defeitos de layout

- src/components/tables/LTableNew.vue
- Adicionado slot para no-data
- LOG-31263
- LOG-30550
> (LOG-31263) - Adicionado slot para no-data

- docs/stories/components/inputs/LDropdownCheckbox.stories.js
- src/components/inputs/LDropdownCheckbox.vue
- adição de props para texto do placeholder e textos de placeholder e selectAll do checkboxList
- LOG-31455
- LOG-29061
> (LOG-31455) Novas props para o LDropdownCheckbox

- docs/stories/components/inputs/LDatePickerMonth.stories.js
- enum/date.enum.ts
- src/components/inputs/LDatePickerMonth.vue
- src/locale/en.js
- src/locale/pt.js
- Adição de tradução aos períodos
- Adição de prop itemsColor
- Documentação
- LOG-32243
- LOG-32244
> (LOG-19128) Ajustes no LDatePickerMonth

- docs/stories/components/charts/LBarChart.stories.js
- src/components/charts/LBarChart.vue
- src/components/charts/LBarChartLine.vue
- test/components/charts/lBarChart.spec.ts
- Criação da ação de click para linha do BarChartLine
- Criação de testes unitários
- LOG-31836
- LOG-31954
> (LOG-32395) Criação evento de click sobre a linha do BarLineChart para filtro automático

- src/components/inputs/LInputLoaded.vue
- test/components/inputs/lInputLoaded.spec.ts
- Correção da chamada de função do PlaceHolder.
- LOG-24214
- LOG-26627
> (LOG-32871) - Correção da chamada de função do PlaceHolder.

- docs/stories/components/inputs/LInputLoaded.stories.js
- src/components/inputs/LInputLoaded.vue
- test/components/inputs/lInputLoaded.spec.ts
- Alteração no componente(LInputLoaded)
- Alteração na doc
- Alteração no teste unitário
- LOG-33174
- LOG-33191
> (LOG-33174) Alteração para incluir disabled no component(LInputLoaded)

- docs/stories/components/inputs/LInputTag.stories.js
- src/components/inputs/LInputTag.vue
- test/components/inputs/lInputTag.spec.ts
- Alteração no component
- Criação de teste unitário
- Alteração da documentação
- LOG-33400
- LOG-33405
> (LOG-33400) Inclusão de label no input

- docs/stories/components/inputs/LDatePickerDay.stories.js
- src/components/inputs/LDatePickerDay.vue
- test/components/inputs/lDatePickerDay.spec.ts
- Criado prop para limitar por anos o período de seleção
- LOG-32513
- LOG-32820
> (LOG-33692) - Adicionar limitação por anos no datepicker

- docs/stories/components/inputs/LCheckboxNew.stories.js
- src/components/inputs/LCheckboxNew.vue
- src/components/inputs/index.js
- test/components/inputs/lCheckboxNew.spec.ts
- Criação do componente
- Criação de teste
- Criação de documentação
- LOG-33354
- LOG-33398
> (LOG-33354) - Componente de checkbox

- docs/stories/components/tables/LTableNew.stories.js
- src/components/tables/LTableNew.vue
- test/components/tables/lTableNew.spec.ts
- Adicionando toggleCheckboxOnRowClick
- LOG-33103
- LOG-33487
> (LOG-33103) Adicionando clique na linha p/ marcar checkbox

- src/components/inputs/LInputLoaded.vue
- Adicionando $listeners no LInputLoaded.vue
- LOG-32691
- LOG-34474
> (LOG-34475) - Adicionando $listeners no LInputLoaded.vue

- docs/stories/components/buttons/LButton.stories.js
- docs/stories/components/buttons/LButtonIcon.stories.js
- docs/stories/components/buttons/LButtonNew.stories.js
- src/assets/scss/_variables.scss
- src/components/buttons/LButtonNew.vue
- src/components/buttons/index.js
- test/components/buttons/lButtonNew.spec.ts
- Criação de novo LButton 
- Criação de variantes específicas de acordo com o protótipo
- Nova documentação e testes unitários
- LOG-29409
- LOG-34190
> (LOG-29409) Criação LButtonNew

- docs/stories/components/tables/LTableNew.stories.js
- src/components/tables/LTableNew.vue
- Fix table checkbox colors
- LOG-33102
- LOG-35359
> (LOG-33102) - Changed table checkbox colors

- docs/stories/components/inputs/LInputLoaded.stories.js
- docs/stories/components/inputs/LInputTag.stories.js
- src/assets/scss/_inputs.scss
- src/assets/scss/_main.scss
- src/components/inputs/LInputLoaded.vue
- src/components/inputs/LInputTag.vue
- test/components/inputs/lInputLoaded.spec.ts
- test/components/inputs/lInputTag.spec.ts
- Fix input height allowing grow
- LOG-35396
- LOG-35409
> (LOG-35396) - Fix input height allowing grow

- src/components/inputs/LCheckboxList.vue
- test/components/inputs/lCheckboxList.spec.ts
- Alteração para o trigger do limpar campos filtros funcionar
- LOG-35443
- LOG-28423
> (LOG-35443) Alteração para o trigger do limpar campos filtros funcionar

- .storybook/preview-head.html
- docs/stories/components/buttons/LButtonNew.stories.js
- src/components/buttons/LButtonNew.vue
- test/components/buttons/lButtonNew.spec.ts
- test/utils/size.spec.ts
- utils/size.util.ts
- Ajustando mecanismo height utilizado nos inputs para conseguir reaproveitar
- Removendo padding desnecessário
- Removendo !important desnecessários
- Font-size em rem
- Renomeando prop
- LOG-35499
- LOG-35611
> (LOG-35499) Melhorias LButtonNew

- docs/stories/components/inputs/LDatePickerDay.stories.js
- docs/stories/components/inputs/LDatePickerMonth.stories.js
- docs/stories/components/inputs/LInputLoaded.stories.js
- src/components/inputs/LDatePickerDay.vue
- src/components/inputs/LDatePickerMonth.vue
- src/components/inputs/LInputLoaded.vue
- Adicionado mecanismo para alterar a cor de todos os elementos do datepicker de acordo com a prop já existente itemsColor
- Adicionado mecanismo para alterar a cor da borda do datepicker
- Adicionado mecanismo para dar toggle no icone de dropdown presente no datepicker por padrão
- LOG-34819
- LOG-36792
> (LOG-34819) Melhoria mecanismo de cores Datepickers

- docs/stories/components/charts/LBarChart.stories.js
- docs/stories/components/charts/LLinearChart.stories.js
- src/components/charts/LBarChartLine.vue
- src/components/charts/LLinearChartExpand.vue
- src/components/charts/LLinearChartLine.vue
- test/components/charts/lBarChart.spec.ts
- Alterado tooltip padrão nos gráficos
- LOG-36630
- LOG-36953
> (LOG-36630) - Alterado tooltip padrão nos gráficos

- src/components/charts/LBarChartLine.vue
- Adicionada verificação para valores undefined na condição de preenchimento do line no BarChart
- LOG-36281
- LOG-37346
> (LOG-36281) - Adicionada verificação para valores undefined na condição de preenchimento do line no BarChart

- docs/stories/components/tables/LTableNew.stories.js
- src/components/tables/LTableNew.vue
- Adição de prop para possibilitar customizar as cores dos icones da table
- LOG-38458
- LOG-37235
> (LOG-38458) Adição prop iconColors LTableNew

- docs/stories/components/buttons/LButtonNew.stories.js
- src/components/buttons/LButtonNew.vue
- src/components/modal/LModalNew.vue
- Ajustes modal e botão
- LOG-32960
- LOG-37753
> (LOG-32960) - Ajustes modal e botão

- src/components/timeline/LTimeline.vue
- test/components/timeline/lTimeline.spec.ts
- If there are no enough items hide right button
- LOG-38563
- LOG-38559
> (LOG-38563) Change display scroll button

- yarn.lock
- Subir as atualizações de segurança do dependabot.
- LOG-35296
- LOG-42617
> (LOG-35296) Atualização de segurança das dependências

- package.json
- Update index file
- LOG-41669
- LOG-42847
> (LOG-41669) - Update index file

- src/components/tooltip/LTooltip.vue
- Adjust opacity and line-height
- LOG-39836
- LOG-42922
> (LOG-39836) - Adjust opacity and line-height

- docs/stories/components/inputs/LTextField.stories.js
- src/assets/scss/inputs.scss
- src/components/inputs/LTextField.vue
- Adiciona cor para icone append ao focar
- LOG-40957
- LOG-43532
> (LOG-40957) - Adiciona cor para icone append ao focar

- docs/stories/components/inputs/LTextField.stories.js
- src/components/inputs/LTextField.vue
- Corrigido validação de props
- LOG-40957
- LOG-43532
> (LOG-40957) - Corrigido validação de props

- src/components/buttons/LButtonNew.vue
- Retornando classe setada pela prop
- LOG-41633
- LOG-43131
> (LOG-41633) Devolvendo classe removida

- babel.config.js
- docs/stories/components/tooltip/LTooltip.stories.js
- jest.config.js
- package.json
- src/components/tooltip/LTooltip.vue
- test/components/tooltip/lTooltip.spec.ts
- test/utils/string.spec.ts
- utils/string.util.ts
- yarn.lock
- Forçando alinhamento nos tooltips top e bottom
- LOG-43536
- LOG-44514
> (LOG-43536) - Forçando alinhamento nos tooltips top e bottom

- docs/stories/design/colors.stories.mdx
- Tabela de cores
- LOG-45197
- LOG-45349
> (LOG-45197) Documentando cores

- src/components/inputs/LDropdownCheckbox.vue
- Removendo border-radius para não cagar o componente no Shared
- LOG-45554
- LOG-45556
> (LOG-45554) Removendo border-radius LDropdownCheckbox

- .github/workflows/npm-publish.yml
- package.json
feature: release/v2.0.0 - atualização de workflow
> feature: release/v2.0.0 - atualização de workflow

- docs/stories/components/inputs/LInputLoaded.stories.js
- src/components/inputs/LInputLoaded.vue
- test/components/inputs/lInputLoaded.spec.ts
- Alteração no componente
- Alteração teste unitário
- Criação de documentação
- LOG-43123
- LOG-45868
> (LOG-43123) Inclusão de props  input loaded

- docs/stories/components/inputs/LTextArea.stories.js
- src/components/inputs/LTextArea.vue
- test/components/inputs/lTextArea.spec.ts
- Adicionado componente LTextArea
- LOG-41284
- LOG-46260
> (LOG-41284) - Adicionado componente LTextArea

- .prettierignore
- .prettierrc.json
- Configurando o prettier de acordo com o padrão 
- LOG-46117
- LOG-46549
> (LOG-46117) Configuração prettier

- .github/workflows/npm-publish-beta.yml
- .github/workflows/npm-publish.yml
- Ajustando de acordo com o padrão
- LOG-45606
- LOG-47396
> (LOG-45606) Padronizando workflows de deploy

- src/components/inputs/LDropdownCheckbox.vue
- Ajustando layout para voltar ao comportamento esperado
- LOG-48424
- LOG-48427
> (LOG-48424) Ajustes de layout DropdownCheckbox

- docs/stories/components/cards/LCard.stories.js
- docs/stories/components/cards/LCardHeaderNew.stories.js
- docs/stories/components/cards/LCardNew.stories.js
- src/components/cards/LCardHeaderNew.vue
- src/components/cards/LCardNew.vue
- src/components/cards/index.js
- test/components/cards/LCardHeaderNew.spec.ts
- test/components/cards/lCardNew.spec.ts
- Novo card e card header
- Documentação e testes unitários
- LOG-41207
- LOG-48815
> (LOG-41207) Criação novos componentes de card

- docs/stories/components/bars/LProgressBar.stories.js
- src/components/bars/LProgressBar.vue
- test/components/bars/lProgressBar.spec.ts
- Criação de documentação para o componente
- Adicionando mecanismo para reverter o cursor pointer para o normal
- Teste unitário do mecanismo do cursor
- LOG-41195
- LOG-50704
> (LOG-41195) Documentando e Melhorando LProgressBar

- src/components/inputs/LTextArea.vue
- src/components/inputs/index.js
- Adicionado eventos para o LTextArea
- Adicionado chamada para build do componente
- LOG-50553
- LOG-50759
> (LOG-50553) - Adicionado eventos para o LTextArea

- .github/workflows/npm-publish-beta.yml
- Removendo paths-ignore da publish beta para que eu consiga gerar uma versão beta -0 igual à estável
- LOG-51080
- LOG-51858
> (LOG-51080) Removendo paths-ignore beta

- .github/workflows/npm-publish-beta.yml
> Adding paths-ignore

- docs/stories/components/inputs/LDropdownCheckbox.stories.js
- src/components/inputs/LDropdownCheckbox.vue
- test/components/inputs/lDropdownCheckbox.spec.ts
- Alteração no componente
- Alteração na doc e testes unitários
- LOG-52069
- LOG-52338
> (LOG-52069) Inclusão de slot no dropdownCheckbox

- src/components/inputs/LDropdownCheckbox.vue
- Inclusão de controle de desabilitar o v-menu LDropdownCheckbox
- LOG-52069
- LOG-52338
> (LOG-52069) Inclusão de controle de desabilitar o v-menu LDropdownCheckbox

- src/components/charts/LGridChart.vue
- test/components/charts/lGridChart.spec.ts
- Ajustado padding
- Espaçamento entre a linha e o icon
- Retirada a ultima borda como no protótipo do figma
- LOG-41465
- LOG-42969
> (LOG-41465) - Ajustes no design do GridChart

- docs/stories/components/charts/LLinearChart.stories.js
- docs/stories/components/charts/LLinearChartTotalValue.stories.js
- src/components/charts/LLinearChart.vue
- src/components/charts/LLinearChartLine.vue
- test/components/charts/lLinearChart.spec.ts
- test/components/charts/lLinearChartLine.spec.ts
- Adicionada uma propriedade para apresentar a lupa que disparaemite evento no linear chart
- LOG-52045
- LOG-52048
> (LOG-52045) - Criar lupa para gráfico LinearChart

- src/components/loadings/LLoading.vue
- Removendo icon antigo e acrescentando novo icon solicitado pelo UX
- LOG-51875
- LOG-51875
> (LOG - 51875) - Adicionado novo design do icon loading

- src/components/loadings/LLoading.vue
- Ajustando o sentido da animação do icon loading 
- LOG-51875
- LOG-51875
> (LOG-51875) - Atualizado o sentido da animação do icon loading

- src/components/charts/LGeneralChart.vue
- Ajustes nos espaçamentos
- LOG-52573
- LOG-52573
> (LOG-52573) - Ajuste de espaçamento

- src/components/inputs/LSelect.vue
- Ajuste da cor do texto
-LOG-52577
- LOG-52577
> (LOG-52577) - Ajuste color texto

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- Melhorias de documentação do PR e template do PR
- LOG-52748
- LOG-53899
> (LOG-52748) Melhoria documentação PRs

- docs/stories/design/colors.stories.mdx
- mixins/colors.mixin.ts
- src/assets/scss/_export.module.scss
- src/assets/scss/_variables.scss
- src/components/charts/LBarChart.vue
- src/components/charts/LLinearChart.vue
- src/components/charts/LLinearChartLine.vue
- src/components/filters/LLabeledChip.vue
- src/components/inputs/LDatePickerDay.vue
- src/components/inputs/LDatePickerMonth.vue
- src/components/inputs/LInputButton.vue
- src/components/inputs/LInputLoaded.vue
- src/components/inputs/LInputSolo.vue
- src/components/inputs/LInputTag.vue
- src/components/inputs/LLabeledInput.vue
- src/components/inputs/LLabeledSelect.vue
- src/components/inputs/LLabeledTextarea.vue
- src/components/inputs/LSelectNamed.vue
- src/components/modal/LModalHeaderNew.vue
- src/components/modal/LModalNew.vue
- src/components/tables/LTableNew.vue
- src/components/timeline/LTimeline.vue
- Criado mixin de cores
- Substituindo chamadas diretas de cores pela do mixin
- LOG-50918
- LOG-54042
> (LOG-50918) Mecanismo de cores por mixin

- src/components/charts/LGeneralChart.vue
- Ajuste de quebra de linha
- LOG-52573
- LOG-52573
> (LOG-52573) - Ajuste de quebra de linha

- src/components/inputs/LInputTag.vue
- test/components/inputs/lInputTag.spec.ts
- Inclusão de props para restringir somente numeros
- LOG-52617
- LOG-56201
> (LOG-52617) Inclusão de props para restringir somente numeros

- docs/stories/components/inputs/LInputTag.stories.js
- Atualizando documentação do LInputLoaded
- LOG-56199
- LOG-56201
> (LOG-56199) Atualizando documentação do LInputLoaded

- .storybook/preview-head.html
- Sobrepondo o font-family da classe .v-application para que os componentes que puxam fonte do Vuetify fiquem com a family correta.
- LOG-52722
- LOG-57351
> (LOG-52722) Sobrepondo font-family vuetify doc

- .storybook/preview-head.html
- docs/stories/components/alerts/LToast.stories.js
- test/components/alerts/LToast.spec.ts
- Corrigido LToast fora da story
- LOG-55305
- LOG-57361
> (LOG-55305) - Corrigido LToast fora da story

- enum/datepicker.enum.ts
- test/components/inputs/lDatePickerDay.spec.ts
- Ajuste no formato de data americano do datepicker.
- [LOG-57518](https://logcomex.atlassian.net/browse/LOG-57518)
- [LOG-58338](https://logcomex.atlassian.net/browse/LOG-58338)
> (LOG-57518) Trazer data em formato americano

- docs/stories/components/inputs/LCombobox.stories.js
- docs/stories/components/inputs/LSelect.stories.js
- docs/stories/components/inputs/LTextField.stories.js
- src/assets/scss/_globals.scss
- src/assets/scss/inputs.scss
- test/components/inputs/lCombobox.spec.ts
- test/components/inputs/lTextField.spec.ts
- Corrigindo inconsistências visuais envolvendo:
- LCombobox com placeholder e prop "chips"
- LCombobox com prop "small-chips"
- Inputs sem a prop dense
- Adição de mais exemplos na documentação 
- Adição de mais um case de teste no LTextField fechando 100% de coverage
- LOG-58098
- LOG-58296
> (LOG-58098) Melhorias/correções visuais inputs

- src/components/cards/LCardHeaderNew.vue
- Espaçamento do header padrão de card está errado, esse PR deixa ele correto.
- LOG-57115
- LOG-58533
> (LOG-57115) Ajustando espaçamento com/sem prepend LCardHeaderNew

- src/assets/scss/inputs.scss
- Revertendo a query para um menos específico. É uma correção pois no Comex estava quebrando.
- LOG-58836
- LOG-58839
> (LOG-58836) Revertendo query disabled

- .github/workflows/percy.yml
- Adicionado target branch no yml
- LOG-55573
- LOG-58608
> (LOG-55573) - Adicionado target branch no yml

- src/assets/scss/inputs.scss
- src/components/buttons/LButtonNew.vue
- src/components/inputs/LInputLoaded.vue
- src/components/inputs/LTextField.vue
- Ajustando para classes --small e --large ficarem sempre por últimas
- LOG-59665
- LOG-59666
> (LOG-59665) Fix: Classes --small e --large não aplicando

- src/components/cards/LCard.vue
- src/components/cards/LCardHeader.vue
- Alerta de depreciação em componente que será removido no futuro
- LOG-59737
> (LOG-59737) Depreciando LCard e LCardHeader

- src/components/inputs/LCheckboxList.vue
- src/components/inputs/LDropdownCheck.vue
- Substituindo uso do LInputSolo que será removido em breve
- Subindo warn na utilização do LDropdownCheck que está marcado para remoção
- LOG-59582
- LOG-59875
> (LOG-59582) Substituindo input depreciado e add alerta de depreciação

- src/components/inputs/LCheckboxNew.vue
- Adicionando cor na label do LCheckboxNew para conseguir substituir o LCheckbox no LSFieldManager
- LOG-59582
- LOG-59875
> (LOG-59582) Add cor label LCheckboxNew

- src/components/timeline/LTimeline.vue
- Criação de mecanismo para verificar caso esteja no mobile
- Alteração de responsividade da time line
- LOG-57281
- LOG-59905
> (LOG-57281) Adiçao de validação para exibir as setinhas caso estiver no mobile e responsividade da timeline

- src/components/timeline/LTimeline.vue
- Correção para botão não aparecer quando se chega ao fim do scroll
- Remoção do V-deeps
- LOG-60488
- LOG-59905
> (LOG-60488) Correção dos botões da timeline

- src/components/charts/LLinearChart.vue
- Adicionado item para o slot LLinearChart
- LOG-57140
- LOG-57965
> (LOG-57140) - Adicionado item para o slot LLinearChart

- docs/stories/components/timeline/LTimeline.stories.js
- src/components/timeline/LTimeline.vue
- test/components/timeline/lTimeline.spec.ts
- Ajustando apresentação do icone de proximo
- LOG-61754
- LOG-61754
- [] Documentação atualizada
> (LOG-61754) - Ajustar icone de proximo na timeline

- src/components/timeline/LTimeline.vue
- Correção para iniciar com a seta sendo mostrada
- LOG-61754
- LOG-61754
> (LOG-61754) Correção para iniciar com a seta sendo mostrada

- src/components/timeline/LTimeline.vue
- Iniciando componente com foco no ultimo item
- Ajuste para não exibir a seta da direita quando estiver no final do scroll
- LOG-62183
- LOG-62183
> (LOG-62183) - Melhoria componente de timeline

- src/components/inputs/LDatePickerMonth.vue
- test/components/inputs/lDatePickerMonth.spec.ts
- Exibindo período selecionado em ordem ascendente
- Teste unitário
- LOG-63060
- LOG-63860
> (LOG-63060) -  Permitindo pesquisar data final antes que data inicial

- docs/stories/components/charts/LLinearChart.stories.js
- src/components/charts/LLinearChart.vue
- src/components/charts/LLinearChartExpand.vue
- src/components/charts/LLinearChartLine.vue
- test/components/charts/LLinearChart/lLinearChartLineNew.spec.ts
- test/components/charts/LLinearChart/mocks.ts
- test/components/charts/lLinearChart.spec.ts
- test/components/charts/lLinearChartExpand.spec.ts
- test/components/charts/lLinearChartLine.spec.ts
- Melhorias em mecanismos já existentes que não funcionavam corretamente
- Adição de novas propriedades no "data": resultContent e description
- LOG-62826
- LOG-62832
> (LOG-62826) Melhorias LLinearChart e LLinearChartLine

- docs/stories/components/charts/LCircularChart.stories.js
- src/components/charts/LCircularChart.vue
- test/components/charts/lCircularChart.spec.ts
- Adicionando mais possibilidades ao componente com: Remoção da obrigatoriedade do value para renderizar, adição de icons e mecanismo para tradução
- Melhorias de documentação
- Testes unitários refatorados para Testing Library
- LOG-64930
- LOG-64933
> (LOG-64357) Melhorias/refactor LCircularChart

- docs/stories/components/timeline/LTimeline.stories.js
- src/components/timeline/LTimeline.vue
- test/components/timeline/lTimeline.spec.ts
- Adicionando slot de noData
- Testes unitários
- Documentação
- LOG-33747
- LOG-XX
> (LOG-33747) - Adicionando slot no componente de linha do tempo

- src/components/inputs/LDatePickerMonth.vue
- Utilizando clone de this.monthsPeriod para ordenar os meses selecionados
- LOG-68536
- LOG-68536
> (LOG-68536) - Erro ao acessar em ambiente de desenvolvimento

- src/components/cards/LCardHeaderNew.vue
-  Ajuste de font solicitado pela designer
- LOG-67233
- LOG-67233
- [] Feature anotada na release note
> (LOG-67233) - Ajuste de font solicitado pela designer

- src/components/modal/LModalNew.vue
- Adicionado merge das props e attrs
- LOG-67663
> (LOG-67663) - Adicionado merge das props e attrs

- src/components/charts/LLinearChartLine.vue
- Ajustado width e irmandade das divs para estarem na mesma linha
- LOG-67236
- LOG-67236
> (LOG-67236) - Ajustado width e posicionamento dos valores do chart LinearLineChart

- docs/stories/components/inputs/LCheckboxNew.stories.js
- src/components/inputs/LCheckboxNew.vue
- test/components/inputs/lCheckboxNew.spec.ts
- Adicionando hook no LCheckboxNew para não setar o id e também repassar
- LOG-71711
- LOG-XX
> (LOG-71711) Incluindo hook desabilitando inheritAttrs

- src/components/charts/LLinearChartLine.vue
- Retornando como era a estrutura do gráfico linear chart
- Pensando numa nova melhoria, retornar como era antes para não haver bugs futuro em novos produtos
- LOG-67236
- LOG-67236
> (LOG-67236) - Retornando como era a estrutura do gráfico linear chart

- src/components/charts/LLinearChartExpand.vue
- test/components/charts/lLinearChartExpand.spec.ts
- Add prop retractText para setar o texto usado para recolher o llinearCharExpand. O default é null e caso esta propriedade não seja enviada, será mostrado o texto atual em $t('ayla.retract')
- Testes unitários
- LOG-71043
- LOG-71043
> (LOG-71043) - Mudar de "Hide" para "To Retract" no gráfico de Prováveis exportadores

- docs/stories/components/modals/LModalHeaderNew.stories.js
- src/components/modal/LModalHeaderNew.vue
- test/components/modal/LModalHeaderNew.spec.ts
- Add props Subtitle
- Add documentação
- Add testes unitários 
- LOG-80170
- LOG-XX
> (LOG-80170) - Add subtitulo no header da modal

- docs/stories/components/modals/LModalFooterNew.stories.js
- src/components/modal/LModalFooterNew.vue
- test/components/modal/LModalFooterNew.spec.ts
- Add slot
- Add documentação
- Add testes
- LOG-80171
- LOG-XX
> (LOG-80171) - Adicionando slot no footer da modal

- package.json
- Release v3.6.1-7
- LOG-XX
- LOG-XX
> (homol) Release v3.6.1-7

- .storybook/preview-head.html
- src/assets/scss/_globals.scss
- src/assets/scss/inputs.scss
- src/components/buttons/LButtonNew.vue
- src/components/charts/LBarChartLine.vue
- src/components/charts/LLinearChartLine.vue
- src/components/timeline/LTimeline.vue
- Removendo fonte fixa do pacote
- LOG-80743
- LOG-XX
> (LOG-80743) - Removendo fonte fixa

- package.json
> (homol) Atualizando versão do pacote

- src/components/inputs/LCombobox.vue
> (LOG-80743) - teste

- src/components/inputs/LCombobox.vue
Reverts comexio/design-system#441
> Revert "(LOG-80743) - teste"

- package.json
- test/components/alerts/LHeaderAlertContent.spec.ts
> (LOG-80743) - Atualizando versão

- docs/stories/components/alerts/LToast.stories.js
> (fix) Removendo espaços

- package.json
> (release/v3.6.1-12) Atualizando versão já no package.json

- docs/stories/components/cards/LCardNew.stories.js
> (homol) Remoção de espaçamento desnecessário

- package.json
> (LOG-80743) - att versao

- package.json
> (update/version) Atualizando versão no package.json

- docs/stories/components/inputs/LTextArea.stories.js
- docs/stories/components/inputs/LTextField.stories.js
> (fix/lint) Corrigindo lint

- .github/workflows/npm-publish.yml
- Alterando lib publish library
- LOG-XX
- LOG-XX
> (fix/publish-library) Alterando lib publish library

- src/components/buttons/LButtonNew.vue
- Adição de condição de remoção de important no dark--mode
- LOG-82294
- LOG-82294
> (LOG-82294) - Adição de condição de remoção de important no dark--mode

- docs/stories/components/inputs/LDatePickerDay.stories.js
- src/components/inputs/LDatePickerDay.vue
- test/components/inputs/lDatePickerDay.spec.ts
O Que
Como mostra neste novo protótipo criado, deve ser incluido no componente LDatePicker o slot do footer para permitir o uso do trigger.
Por que
Para a possibilidade de usar o datepicker como um filtro.
Resultado
DatePicker possibilidade de conter botões do footer.
- LOG-XX
- LOG-XX
> (LOG-86343) - Adicionando opção de fechar o menu (DatePickerDay)

- src/components/inputs/LCheckboxNew.vue
- Alteração do componete para corrigir warnings no console, relacionado a tipagem
- LOG-XX
- LOG-XX
> Fix: Alteração do componete para corrigir warnings no console, relacionado a tipagem

- docs/stories/components/inputs/LDropdownCheckbox.stories.js
- src/components/inputs/LDropdownCheckbox.vue
- test/components/inputs/lDropdownCheckbox.spec.ts
- Criação/alteração dos componentes
- Criação dos testes unitários
- Criação de documentação
- LOG-104170
- LOG-XX
> (LOG-104170) Alterar no componente LDropdownCheckbox para incluir slot no button

- src/assets/scss/inputs.scss
- Correção do css do select para não alterar o ícone de clearable
- LOG-107303
- LOG-XX
> (LOG-107303) Correção do css do select para não alterar o ícone de clearable

- package.json
> (update-version) Atualizando versão para 3.7.1-6

- package.json
> feature: release/v3.7.1-7

- src/components/alerts/LHeaderAlert.vue
> (fix) Fix version package
